platform :ios, '16.0'
use_frameworks! :linkage => :static

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
  pod 'CapacitorClipboard', :path => '../../../node_modules/@capacitor/clipboard'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/@capacitor/status-bar'
  pod 'K2Plugin', :path => '../../../node_modules/k2-plugin'
end

target 'App' do
  capacitor_pods
end

target 'PacketTunnelExtension' do
  use_frameworks! :linkage => :static
  # NE target only needs gomobile xcframework — NO Capacitor
end
