/**
 * Bridge API contract gate (spec: docs/superpowers/specs/2026-08-14-web-ota-design.md §4).
 *
 * WHY: the 2026-03 incident (`git show c27fd926`) — a hot-updated webapp called
 * `storageGet`, which the installed natives didn't have, and auth broke fleet-wide.
 * Root cause: `min_native` was hand-written, and nothing versioned the bridge
 * surface. This gate snapshots the ENTIRE named-method surface into a committed
 * golden; any drift without a BRIDGE_API_VERSION bump is a red test.
 *
 * Golden: contracts/bridge-api.json — GENERATED, committed, read-only by default.
 * Regen (only after an intentional bridge change + version bump):
 *   cd webapp && UPDATE_BRIDGE_CONTRACT=1 npx vitest run src/types/__tests__/bridge-contract.test.ts
 *
 * Pattern follows api/contract_export_test.go: live values only (TS compiler API
 * over definitions.ts — never a hand-copied list), empty extraction hard-fails
 * (a gate that extracts nothing is a gate that is always green).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { describe, it, expect, assert } from 'vitest';
import { BRIDGE_API_VERSION } from '../bridge-version';
// Imported, never re-derived: the publish-time gate in web-ota-manifest.mjs
// compares floor vs version with this exact function, so a change to the
// comparison can never silently split the two gates apart.
// @ts-expect-error — plain .mjs CI script, no type declarations
import { compareBase } from '../../../../scripts/ci/web-ota-manifest.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../../../..');
const definitionsPath = path.join(repoRoot, 'mobile/plugins/k2-plugin/src/definitions.ts');
const goldenPath = path.join(repoRoot, 'contracts/bridge-api.json');
const floorPath = path.join(repoRoot, 'contracts/webapp-support-floor.json');
const mainRsPath = path.join(repoRoot, 'desktop/src-tauri/src/main.rs');
const REGEN_CMD =
  'cd webapp && UPDATE_BRIDGE_CONTRACT=1 npx vitest run src/types/__tests__/bridge-contract.test.ts';

/** Extract the Tauri named-command table from main.rs generate_handler![...]. */
function extractTauriCommands(mainRs: string): string[] {
  const m = mainRs.match(/generate_handler!\[([\s\S]*?)\]/);
  if (!m) throw new Error('generate_handler![...] not found in desktop/src-tauri/src/main.rs');
  return m[1]
    .split('\n')
    .map((line) => line.replace(/\/\/.*$/, ''))
    .join('\n')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => s.split('::').pop()!)
    .sort();
}

/** Extract the Capacitor bridge surface from definitions.ts via the TS AST. */
function extractCapacitorContract(source: string): { methods: string[]; events: string[] } {
  const sf = ts.createSourceFile('definitions.ts', source, ts.ScriptTarget.Latest, true);
  const methods: string[] = [];
  const events: string[] = [];
  sf.forEachChild((node) => {
    if (!ts.isInterfaceDeclaration(node) || node.name.text !== 'K2PluginInterface') return;
    for (const member of node.members) {
      if (!ts.isMethodSignature(member) || !ts.isIdentifier(member.name)) continue;
      const name = member.name.text;
      if (name === 'addListener') {
        const p = member.parameters[0];
        if (p?.type && ts.isLiteralTypeNode(p.type) && ts.isStringLiteral(p.type.literal)) {
          events.push(p.type.literal.text);
        }
      } else if (!methods.includes(name)) {
        methods.push(name);
      }
    }
  });
  return { methods: methods.sort(), events: events.sort() };
}

function buildLiveContract() {
  const capacitor = extractCapacitorContract(readFileSync(definitionsPath, 'utf8'));
  // Guard against a silently-broken extractor: an empty table would make this
  // gate forever-green (same failure mode api/contract_export_test.go guards).
  expect(capacitor.methods.length).toBeGreaterThanOrEqual(20);
  expect(capacitor.events.length).toBeGreaterThanOrEqual(3);
  const tauriCommands = extractTauriCommands(readFileSync(mainRsPath, 'utf8'));
  expect(tauriCommands.length).toBeGreaterThanOrEqual(15); // forever-green guard
  return {
    _generated:
      `GENERATED by webapp/src/types/__tests__/bridge-contract.test.ts. Do not hand-edit. Regen: ${REGEN_CMD}`,
    bridgeApiVersion: BRIDGE_API_VERSION,
    capacitor,
    tauriCommands,
  };
}

describe('bridge API contract gate', () => {
  it('bridge surface matches committed golden (bump BRIDGE_API_VERSION on change)', () => {
    const live = buildLiveContract();
    const liveJson = JSON.stringify(live, null, 2) + '\n';

    if (process.env.UPDATE_BRIDGE_CONTRACT === '1') {
      writeFileSync(goldenPath, liveJson);
      console.log(`UPDATE_BRIDGE_CONTRACT=1: wrote ${goldenPath}`);
      return;
    }

    expect(
      existsSync(goldenPath),
      `contracts/bridge-api.json missing — it must be committed to git. Generate: ${REGEN_CMD}`,
    ).toBe(true);
    const golden = JSON.parse(readFileSync(goldenPath, 'utf8'));

    const surfaceChanged =
      JSON.stringify(golden.capacitor) !== JSON.stringify(live.capacitor) ||
      JSON.stringify(golden.tauriCommands) !== JSON.stringify(live.tauriCommands);
    if (surfaceChanged && golden.bridgeApiVersion === BRIDGE_API_VERSION) {
      assert.fail(
        `Bridge surface changed WITHOUT a BRIDGE_API_VERSION bump.\n` +
          `golden.capacitor: ${JSON.stringify(golden.capacitor)}\n` +
          `live.capacitor:   ${JSON.stringify(live.capacitor)}\n` +
          `golden.tauriCommands: ${JSON.stringify(golden.tauriCommands)}\n` +
          `live.tauriCommands:   ${JSON.stringify(live.tauriCommands)}\n\n` +
          `If the change is intentional: bump BRIDGE_API_VERSION in webapp/src/types/bridge-version.ts, ` +
          `gate every use of the new surface behind runtime capability detection (webapp/CLAUDE.md 兼容模型), then regen the golden:\n  ${REGEN_CMD}\n` +
          `If not intentional: revert the definitions.ts change. NEVER hand-edit the golden.`,
      );
    }
    expect(
      golden.bridgeApiVersion,
      `golden bridgeApiVersion (${golden.bridgeApiVersion}) != live BRIDGE_API_VERSION (${BRIDGE_API_VERSION}) — regen: ${REGEN_CMD}`,
    ).toBe(BRIDGE_API_VERSION);
    expect(readFileSync(goldenPath, 'utf8')).toBe(liveJson);
  });

  it('webapp-support-floor.json is valid and never exceeds the shipping shell', () => {
    // R2 (spec §4): the floor is the OLDEST shell set the latest webapp still
    // supports. It does NOT move when BRIDGE_API_VERSION bumps — bumping the
    // floor is an explicit support-drop decision. Two invariants a test can
    // hold, one per dimension of the floor:
    //   bridge  — never newer than the compiled bridge surface
    //   version — never newer than the version being shipped, because the
    //             current shell is by definition inside the supported set. A
    //             floor above it makes that shell skip its OWN web OTA via
    //             min_*, silently (Gate::Skip / "shell below min_linux", no
    //             error surface). desktop/linux sat at 0.4.9 while 0.4.8 was
    //             the shipping version — caught by hand, not by this gate,
    //             which is why the version dimension is now covered here.
    expect(existsSync(floorPath), 'contracts/webapp-support-floor.json missing').toBe(true);
    const floor = JSON.parse(readFileSync(floorPath, 'utf8'));
    for (const key of ['native', 'desktop', 'linux'] as const) {
      expect(floor[key], `webapp-support-floor.json .${key} must be x.y.z`).toMatch(/^\d+\.\d+\.\d+$/);
    }
    expect(
      Number.isInteger(floor.bridge) && floor.bridge >= 1,
      `webapp-support-floor.json .bridge must be a positive integer, got: ${floor.bridge}`,
    ).toBe(true);
    expect(
      floor.bridge,
      `floor.bridge (${floor.bridge}) > BRIDGE_API_VERSION (${BRIDGE_API_VERSION}) — ` +
        `the support floor cannot be newer than the current bridge surface`,
    ).toBeLessThanOrEqual(BRIDGE_API_VERSION);

    const shipping = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8')).version;
    expect(shipping, 'root package.json version must be x.y.z').toMatch(/^\d+\.\d+\.\d+$/);
    for (const key of ['native', 'desktop', 'linux'] as const) {
      expect(
        compareBase(floor[key], shipping),
        `floor.${key} (${floor[key]}) is newer than the shipping version (${shipping}) — ` +
          `that shell would be gated out of its own web OTA by min_${key}`,
      ).toBeLessThanOrEqual(0);
    }
  });

  it('Android native mirror matches BRIDGE_API_VERSION', () => {
    const kt = readFileSync(
      path.join(repoRoot, 'mobile/plugins/k2-plugin/android/src/main/java/io/kaitu/k2plugin/K2PluginUtils.kt'),
      'utf8',
    );
    const m = kt.match(/const val BRIDGE_API_VERSION\s*=\s*(\d+)/);
    expect(m, 'K2PluginUtils.BRIDGE_API_VERSION not found — Android mirror missing').not.toBeNull();
    expect(Number(m![1]), 'Android BRIDGE_API_VERSION drifted from webapp SoT').toBe(BRIDGE_API_VERSION);
  });

  it('Desktop shell mirror matches BRIDGE_API_VERSION', () => {
    // Added 2026-08-16 after the desktop web OTA branch shipped five new Tauri
    // commands with the golden regenerated but no bump — bridge v1 ended up
    // denoting two surfaces. Android/iOS were mirrored here from day one;
    // desktop was not, which is exactly why its drift went unseen.
    const rs = readFileSync(path.join(repoRoot, 'desktop/src-tauri/src/web_ota.rs'), 'utf8');
    const m = rs.match(/const DESKTOP_BRIDGE_VERSION:\s*u32\s*=\s*(\d+)/);
    expect(m, 'DESKTOP_BRIDGE_VERSION not found — desktop mirror missing').not.toBeNull();
    expect(Number(m![1]), 'Desktop DESKTOP_BRIDGE_VERSION drifted from webapp SoT').toBe(
      BRIDGE_API_VERSION,
    );
  });

  it('iOS native mirror matches BRIDGE_API_VERSION', () => {
    const swift = readFileSync(
      path.join(repoRoot, 'mobile/plugins/k2-plugin/ios/Plugin/K2Helpers.swift'),
      'utf8',
    );
    const m = swift.match(/let k2BridgeApiVersion\s*=\s*(\d+)/);
    expect(m, 'k2BridgeApiVersion not found — iOS mirror missing').not.toBeNull();
    expect(Number(m![1]), 'iOS k2BridgeApiVersion drifted from webapp SoT').toBe(BRIDGE_API_VERSION);
  });
});
