package center

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	db "github.com/wordgate/qtoolkit/db"
	"github.com/wordgate/qtoolkit/log"
)

// privateNodeInstallContent 装机协助工单文案。中文面向用户,用"开途/专属线路/路由器",
// 禁裸词 "Kaitu"。运营会在此工单线程内主动协助用户完成路由器安装。
const privateNodeInstallContent = "您好!感谢购买开途专属线路。我们的技术支持会主动联系您,协助完成路由器的安装与配置(刷机、接入专属线路、确认连接)。如需尽快开始,可直接在本工单回复您方便的联系方式与时段,我们会优先安排。"

// privateNodeInstallFeedbackID 给装机工单一个确定性 ID,天然幂等(FeedbackID uniqueIndex)。
func privateNodeInstallFeedbackID(subID uint64) string {
	return fmt.Sprintf("pn-install-%d", subID) // <=36 chars
}

// onPrivateNodeOrderOnboarding 在订单 post-commit 后为专属节点订阅做白手套 onboarding:
// ① 建装机协助工单(确定性 FeedbackID,幂等)② Slack 内部告警 ③ 入队欢迎邮件。
// 全 best-effort:任一失败仅 log + Slack,绝不阻断或回滚订单(钱已收)。
func onPrivateNodeOrderOnboarding(ctx context.Context, subID uint64) {
	var sub PrivateNodeSubscription
	if err := db.Get().First(&sub, subID).Error; err != nil {
		log.Errorf(ctx, "onboarding: load sub %d: %v", subID, err)
		return
	}
	// 用户/邮箱解析仅用于工单 email 字段与欢迎邮件,best-effort:
	// 解析失败不阻断装机工单与 Slack 告警(这两个才是关键路径)。
	var email string
	var user User
	if err := db.Get().Preload("LoginIdentifies").First(&user, sub.UserID).Error; err != nil {
		log.Errorf(ctx, "onboarding: load user %d (continuing without email): %v", sub.UserID, err)
	} else {
		email = getUserEmailFromIdentifies(&user)
	}

	// ① 装机工单(幂等)。
	now := time.Now()
	meta, _ := json.Marshal(map[string]any{
		"type": "private_node_install", "subId": sub.ID, "orderId": sub.OrderID, "region": sub.Region,
	})
	userIDPtr := sub.UserID
	ticket := FeedbackTicket{
		FeedbackID:    privateNodeInstallFeedbackID(sub.ID),
		UDID:          fmt.Sprintf("pn:sub:%d", sub.ID),
		UserID:        &userIDPtr,
		Email:         email,
		Content:       privateNodeInstallContent,
		Status:        "open",
		Meta:          string(meta),
		LastReplyAt:   &now,
		AutoGenerated: true,
	}
	if err := db.Get().Create(&ticket).Error; err != nil {
		if isDuplicateKeyErr(err) {
			log.Debugf(ctx, "onboarding: install ticket for sub=%d already exists", sub.ID)
		} else {
			log.Errorf(ctx, "onboarding: create install ticket sub=%d: %v", sub.ID, err)
		}
	}

	// ② Slack 内部告警(催办)。
	sendCloudSlackNotification(ctx, "Dedicated Line Order — Install Needed",
		fmt.Sprintf("新定制线路客户 user=%d order=%d 已付款,需装机协助 + 节点开通(sub=%d, region=%s)。", sub.UserID, sub.OrderID, sub.ID, sub.Region))

	// ③ 欢迎/装机引导邮件。**入队**而非同步发送:本函数跑在 wordgate webhook 请求路径上,
	// SendTemplatedEmails 对非 zh-CN 用户会内联触发同步 AI 翻译(最长 ~30s),会拖垮 webhook 响应
	// 且 ctx 在 handler 返回后即取消(见 reference_edm_lazy_translation_pitfall)。EnqueueTemplatedEmailTask
	// 推到 Asynq 立即返回,翻译/发送在后台 worker 完成。模板缺失则降级跳过。
	const welcomeSlug = "private-node-welcome"
	if email != "" && templateSlugExists(welcomeSlug) {
		if _, err := EnqueueTemplatedEmailTask(ctx, &SendEmailsRequest{
			BatchID: fmt.Sprintf("pn-welcome-%d", sub.ID),
			Items: []SendEmailItem{{
				Email: email, UserID: sub.UserID, Slug: welcomeSlug,
				Vars: map[string]string{"region": sub.Region},
			}},
		}); err != nil {
			log.Errorf(ctx, "onboarding: enqueue welcome email sub=%d: %v", sub.ID, err)
		}
	} else if email != "" {
		log.Warnf(ctx, "onboarding: welcome template %q missing, skip email for sub=%d", welcomeSlug, sub.ID)
	}
}
