package center

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	db "github.com/wordgate/qtoolkit/db"
	"github.com/wordgate/qtoolkit/log"
	"gorm.io/gorm"
)

// privateNodeInstallContent 装机协助工单文案。中文面向用户,用"开途/专属线路/路由器",
// 禁裸词 "Kaitu"。运营会在此工单线程内主动协助用户完成路由器安装。
const privateNodeInstallContent = "您好!感谢购买开途专属线路。我们的技术支持会主动联系您,协助完成路由器的安装与配置(刷机、接入专属线路、确认连接)。如需尽快开始,可直接在本工单回复您方便的联系方式与时段,我们会优先安排。"
const privateNodeWelcomeSlug = "private-node-welcome"
const privateNodeSlackTitle = "Dedicated Line Order — Install Needed"

// routerInstallContent 路由器版付款后的工单文案(新购只有成品,服务套餐仅续费)。中文用户面用"开途"。
const routerInstallContent = "您好!感谢购买开途路由器版。我们正在为您准备专属出口与路由器:成品路由器将在配置完成后寄出,发货与上线进度可在「我的路由器」页面查看。如有任何问题,直接在本工单回复即可。"
const routerWelcomeSlug = "router-welcome"
const routerSlackTitle = "Router Edition Order — Fulfillment Needed"

// privateNodeInstallFeedbackID 给装机工单一个确定性 ID,天然幂等(FeedbackID uniqueIndex)。
func privateNodeInstallFeedbackID(subID uint64) string {
	return fmt.Sprintf("pn-install-%d", subID) // <=36 chars
}

// privateNodeOnboardingCopy 是"路由器版 vs 定制线路"文案分叉的唯一入口(纯函数,可单测)。
// isRouter 由调用方按"该 sub 是否有 RouterFulfillment"判定。
func privateNodeOnboardingCopy(isRouter bool) (content, ticketType, welcomeSlug, slackTitle string) {
	if isRouter {
		return routerInstallContent, "router_order", routerWelcomeSlug, routerSlackTitle
	}
	return privateNodeInstallContent, "private_node_install", privateNodeWelcomeSlug, privateNodeSlackTitle
}

// onPrivateNodeOrderOnboarding 在订单 post-commit 后为专属节点订阅做白手套 onboarding:
// ① 建装机协助工单(确定性 FeedbackID,幂等)② Slack 内部告警 ③ 入队欢迎邮件。
// 全 best-effort:任一失败仅 log + Slack,绝不阻断或回滚订单(钱已收)。
func onPrivateNodeOrderOnboarding(ctx context.Context, subID uint64) {
	var sub PrivateNodeSubscription
	if err := db.Get().First(&sub, subID).Error; err != nil {
		log.Errorf(ctx, "onboarding: load sub %d: %v", subID, err)
		return
	}
	// 用户/邮箱解析仅用于工单 email 字段与欢迎邮件,best-effort:
	// 解析失败不阻断装机工单与 Slack 告警(这两个才是关键路径)。
	var email string
	var user User
	if err := db.Get().Preload("LoginIdentifies").First(&user, sub.UserID).Error; err != nil {
		log.Errorf(ctx, "onboarding: load user %d (continuing without email): %v", sub.UserID, err)
	} else {
		email = getUserEmailFromIdentifies(&user)
	}

	// 路由器版订单:有发货台账 → 用路由器版文案/类型/欢迎模板;否则保持定制线路原文案。
	var fulfillment RouterFulfillment
	isRouter := false
	if err := db.Get().Where("sub_id = ?", sub.ID).First(&fulfillment).Error; err == nil {
		isRouter = true
	} else if !errors.Is(err, gorm.ErrRecordNotFound) {
		// 非"找不到"的查询错误(如连接失败):按定制线路降级处理,但要留痕——
		// 否则一次数据库抖动会悄悄把路由器订单错发成定制线路文案。
		log.Warnf(ctx, "onboarding: lookup router fulfillment for sub=%d: %v", sub.ID, err)
	}
	content, ticketType, welcomeSlug, slackTitle := privateNodeOnboardingCopy(isRouter)

	// ① 装机工单(幂等)。
	now := time.Now()
	metaFields := map[string]any{
		"type": ticketType, "subId": sub.ID, "orderId": sub.OrderID, "region": sub.Region,
	}
	if isRouter {
		metaFields["hardwareSku"] = fulfillment.HardwareSKU
		metaFields["fulfillmentId"] = fulfillment.ID
	}
	meta, _ := json.Marshal(metaFields)
	userIDPtr := sub.UserID
	ticket := FeedbackTicket{
		FeedbackID:    privateNodeInstallFeedbackID(sub.ID),
		UDID:          fmt.Sprintf("pn:sub:%d", sub.ID),
		UserID:        &userIDPtr,
		Email:         email,
		Content:       content,
		Status:        "open",
		Meta:          string(meta),
		LastReplyAt:   &now,
		AutoGenerated: true,
	}
	if err := db.Get().Create(&ticket).Error; err != nil {
		if isDuplicateKeyErr(err) {
			log.Debugf(ctx, "onboarding: install ticket for sub=%d already exists", sub.ID)
		} else {
			log.Errorf(ctx, "onboarding: create install ticket sub=%d: %v", sub.ID, err)
		}
	}

	// ② Slack 内部告警(催办)。
	sendCloudSlackNotification(ctx, slackTitle,
		fmt.Sprintf("新定制线路客户 user=%d order=%d 已付款,需装机协助 + 节点开通(sub=%d, region=%s)。", sub.UserID, sub.OrderID, sub.ID, sub.Region))

	// ③ 欢迎/装机引导邮件。**入队**而非同步发送:本函数跑在 wordgate webhook 请求路径上,
	// SendTemplatedEmails 对非 zh-CN 用户会内联触发同步 AI 翻译(最长 ~30s),会拖垮 webhook 响应
	// 且 ctx 在 handler 返回后即取消(见 reference_edm_lazy_translation_pitfall)。EnqueueTemplatedEmailTask
	// 推到 Asynq 立即返回,翻译/发送在后台 worker 完成。模板缺失则降级跳过。
	if email != "" && templateSlugExists(welcomeSlug) {
		if _, err := EnqueueTemplatedEmailTask(ctx, &SendEmailsRequest{
			BatchID: fmt.Sprintf("pn-welcome-%d", sub.ID),
			Items: []SendEmailItem{{
				Email: email, UserID: sub.UserID, Slug: welcomeSlug,
				Vars: map[string]string{"region": sub.Region},
			}},
		}); err != nil {
			log.Errorf(ctx, "onboarding: enqueue welcome email sub=%d: %v", sub.ID, err)
		}
	} else if email != "" {
		log.Warnf(ctx, "onboarding: welcome template %q missing, skip email for sub=%d", welcomeSlug, sub.ID)
	}
}
